### ISSUE TITLE
show stops on map

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/tryn-react#19]

**Comment by enginaryum** [comment]
I just made the initial commit for this issue on a new [branch](https://github.com/trynmaps/tryn-react/tree/new-relay-structure-for-visualization). 
Can you have a quick check on my work?

PS: Currently stops return null from api. I added if/else statement inside stop marker function.

**Comment by enginaryum** [comment]
Open a PR for this issue #21

**Comment by enginaryum** [comment]
closing due to #23
