### ISSUE TITLE
replace blue markers with an actual bus facing in the appropriate direction

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/tryn-react#31]
[ideas/details added 3/1/18]
I'm unsure of how we'd represent northbound/southbound - in other transit maps all either buses look the same (Transit) or use really ugly images (Nextbus). I was thinking of using this image I made for a project last year (https://www.facebook.com/transibot/photos/a.632218450301186.1073741826.631950076994690/639876799535351/?type=1&theater) and rotating the "antenna" around the bus as to suggest its direction. Using its SVG we could also colour it according to the route.

**Comment by frhino** [comment]
It has been suggested that using centerline node networks would be a good way to separate directions of travel for vehicles, such as http://test.agrokarta.biz/upwork/streetside/.  Do we need a designer to create a bus icon to replace the blue markers?

**Comment by akeimach** [comment]
I'm testing my implementation which tilts a bus icon based on heading. And I can flip the icon direction if I separate the vehicle markers layer in two -- a layer for east bound and one for west bound.

I'm new to this project, how do I go about working on this? Can I assign myself to this ticket? or commit my code for you to review?

**Comment by EddyIonescu** [comment]
Hey @akeimach, that sounds great - we have an onboarding guide that covers the contributing process (tldr you can just assign this issue to yourself, start your branch name with this issue's number, and link this issue to your PR).
